name: Bazel Monorepo Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  bazel-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Restore Bazel cache
      - name: Restore Bazel cache
        uses: actions/cache@v4
        with:
          path: |
            .bazel-cache
            .bazel-repo-cache
          key: bazel-${{ runner.os }}-${{ hashFiles('**/BUILD.bazel', 'WORKSPACE', '.bazelrc') }}
          restore-keys: |
            bazel-${{ runner.os }}-

      # Install Node (Bazel will still manage toolchain internally)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Build Zomato app
      - name: Build Zomato
        run: |
          bazel build //apps/zomato:zomato

      # Build Swiggy app
      - name: Build Swiggy
        run: |
          bazel build //apps/swiggy:swiggy
